//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.26 at 07:43:35 PM IST 
//


package com.tip.suppliermasterdata.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntitlementPoValidDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntitlementPoValidDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PO_Valid_For" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="PO_Valid_For_Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntitlementPoValidDetails", propOrder = {
    "poValidFor",
    "poValidForValue"
})
public class EntitlementPoValidDetails {

    @XmlElement(name = "PO_Valid_For")
    protected Integer poValidFor;
    @XmlElement(name = "PO_Valid_For_Value")
    protected String poValidForValue;

    /**
     * Gets the value of the poValidFor property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPOValidFor() {
        return poValidFor;
    }

    /**
     * Sets the value of the poValidFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPOValidFor(Integer value) {
        this.poValidFor = value;
    }

    /**
     * Gets the value of the poValidForValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOValidForValue() {
        return poValidForValue;
    }

    /**
     * Sets the value of the poValidForValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOValidForValue(String value) {
        this.poValidForValue = value;
    }

}
