//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.26 at 07:43:35 PM IST 
//


package com.tip.suppliermasterdata.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SupplierCapMotOptions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SupplierCapMotOptions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Mot_Ind" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Mot_Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupplierCapMotOptions", propOrder = {
    "motInd",
    "motDesc"
})
public class SupplierCapMotOptions {

    @XmlElement(name = "Mot_Ind")
    protected Integer motInd;
    @XmlElement(name = "Mot_Desc")
    protected String motDesc;

    /**
     * Gets the value of the motInd property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMotInd() {
        return motInd;
    }

    /**
     * Sets the value of the motInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMotInd(Integer value) {
        this.motInd = value;
    }

    /**
     * Gets the value of the motDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotDesc() {
        return motDesc;
    }

    /**
     * Sets the value of the motDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotDesc(String value) {
        this.motDesc = value;
    }

}
