//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.21 at 03:25:11 PM IST 
//


package com.tip.supplier.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AllCapabilitiesResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AllCapabilitiesResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EquipmentDataResponseList" type="{http://www.example.org/AllCapabilities}EquipmentDataObject" maxOccurs="unbounded"/>
 *         &lt;element name="AuxiliaryEquipmentDataResponseList" type="{http://www.example.org/AllCapabilities}AuxiliaryEquipmentDataObject" maxOccurs="unbounded"/>
 *         &lt;element name="AdditionalCapabilitiesDataResponseList" type="{http://www.example.org/AllCapabilities}AdditionalCapabilitiesDataObject" maxOccurs="unbounded"/>
 *         &lt;element name="InspectionCapabilitiesDataResponseList" type="{http://www.example.org/AllCapabilities}InspectionCapabilitiesObject" maxOccurs="unbounded"/>
 *         &lt;element name="RepairBuilderCapabilitiesDataResponseList" type="{http://www.example.org/AllCapabilities}RepairBuilderCapabilitiesObject" maxOccurs="unbounded"/>
 *         &lt;element name="CapabilitiesStatusResponseList" type="{http://www.example.org/AllCapabilities}CapabilitiesStatusObject" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AllCapabilitiesResponse", propOrder = {
    "equipmentDataResponseList",
    "auxiliaryEquipmentDataResponseList",
    "additionalCapabilitiesDataResponseList",
    "inspectionCapabilitiesDataResponseList",
    "repairBuilderCapabilitiesDataResponseList",
    "capabilitiesStatusResponseList"
})
public class AllCapabilitiesResponse {

    @XmlElement(name = "EquipmentDataResponseList", required = true)
    protected List<EquipmentDataObject> equipmentDataResponseList;
    @XmlElement(name = "AuxiliaryEquipmentDataResponseList", required = true)
    protected List<AuxiliaryEquipmentDataObject> auxiliaryEquipmentDataResponseList;
    @XmlElement(name = "AdditionalCapabilitiesDataResponseList", required = true)
    protected List<AdditionalCapabilitiesDataObject> additionalCapabilitiesDataResponseList;
    @XmlElement(name = "InspectionCapabilitiesDataResponseList", required = true)
    protected List<InspectionCapabilitiesObject> inspectionCapabilitiesDataResponseList;
    @XmlElement(name = "RepairBuilderCapabilitiesDataResponseList", required = true)
    protected List<RepairBuilderCapabilitiesObject> repairBuilderCapabilitiesDataResponseList;
    @XmlElement(name = "CapabilitiesStatusResponseList", required = true)
    protected List<CapabilitiesStatusObject> capabilitiesStatusResponseList;

    /**
     * Gets the value of the equipmentDataResponseList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentDataResponseList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentDataResponseList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EquipmentDataObject }
     * 
     * 
     */
    public List<EquipmentDataObject> getEquipmentDataResponseList() {
        if (equipmentDataResponseList == null) {
            equipmentDataResponseList = new ArrayList<EquipmentDataObject>();
        }
        return this.equipmentDataResponseList;
    }

    /**
     * Gets the value of the auxiliaryEquipmentDataResponseList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the auxiliaryEquipmentDataResponseList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuxiliaryEquipmentDataResponseList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuxiliaryEquipmentDataObject }
     * 
     * 
     */
    public List<AuxiliaryEquipmentDataObject> getAuxiliaryEquipmentDataResponseList() {
        if (auxiliaryEquipmentDataResponseList == null) {
            auxiliaryEquipmentDataResponseList = new ArrayList<AuxiliaryEquipmentDataObject>();
        }
        return this.auxiliaryEquipmentDataResponseList;
    }

    /**
     * Gets the value of the additionalCapabilitiesDataResponseList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalCapabilitiesDataResponseList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalCapabilitiesDataResponseList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalCapabilitiesDataObject }
     * 
     * 
     */
    public List<AdditionalCapabilitiesDataObject> getAdditionalCapabilitiesDataResponseList() {
        if (additionalCapabilitiesDataResponseList == null) {
            additionalCapabilitiesDataResponseList = new ArrayList<AdditionalCapabilitiesDataObject>();
        }
        return this.additionalCapabilitiesDataResponseList;
    }

    /**
     * Gets the value of the inspectionCapabilitiesDataResponseList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inspectionCapabilitiesDataResponseList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInspectionCapabilitiesDataResponseList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InspectionCapabilitiesObject }
     * 
     * 
     */
    public List<InspectionCapabilitiesObject> getInspectionCapabilitiesDataResponseList() {
        if (inspectionCapabilitiesDataResponseList == null) {
            inspectionCapabilitiesDataResponseList = new ArrayList<InspectionCapabilitiesObject>();
        }
        return this.inspectionCapabilitiesDataResponseList;
    }

    /**
     * Gets the value of the repairBuilderCapabilitiesDataResponseList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the repairBuilderCapabilitiesDataResponseList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepairBuilderCapabilitiesDataResponseList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RepairBuilderCapabilitiesObject }
     * 
     * 
     */
    public List<RepairBuilderCapabilitiesObject> getRepairBuilderCapabilitiesDataResponseList() {
        if (repairBuilderCapabilitiesDataResponseList == null) {
            repairBuilderCapabilitiesDataResponseList = new ArrayList<RepairBuilderCapabilitiesObject>();
        }
        return this.repairBuilderCapabilitiesDataResponseList;
    }

    /**
     * Gets the value of the capabilitiesStatusResponseList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capabilitiesStatusResponseList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCapabilitiesStatusResponseList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CapabilitiesStatusObject }
     * 
     * 
     */
    public List<CapabilitiesStatusObject> getCapabilitiesStatusResponseList() {
        if (capabilitiesStatusResponseList == null) {
            capabilitiesStatusResponseList = new ArrayList<CapabilitiesStatusObject>();
        }
        return this.capabilitiesStatusResponseList;
    }

}
