//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.21 at 09:21:51 PM IST 
//


package com.tip.supplier.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MsuDataObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MsuDataObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="supplierId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="msuSeqId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="groupDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subGroupId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="subGroupDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="itemId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="itemDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reg_Nr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Fleet_Nr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Direct_Contact_Ind" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Dialing_Cd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Phone_Nr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Bus_Hr_Cov_Rad" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Non_Bus_Hr_Cov_Rad" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Bus_Hr_Area" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Ops_Area" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Is_Active" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Is_Enabled" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MsuDataObject", propOrder = {
    "supplierId",
    "msuSeqId",
    "groupId",
    "groupDesc",
    "subGroupId",
    "subGroupDesc",
    "itemId",
    "itemDesc",
    "regNr",
    "fleetNr",
    "directContactInd",
    "dialingCd",
    "phoneNr",
    "busHrCovRad",
    "nonBusHrCovRad",
    "busHrArea",
    "opsArea",
    "isActive",
    "isEnabled"
})
public class MsuDataObject {

    protected Integer supplierId;
    protected Integer msuSeqId;
    protected Integer groupId;
    protected String groupDesc;
    protected Integer subGroupId;
    protected String subGroupDesc;
    protected Integer itemId;
    protected String itemDesc;
    @XmlElement(name = "Reg_Nr")
    protected String regNr;
    @XmlElement(name = "Fleet_Nr")
    protected String fleetNr;
    @XmlElement(name = "Direct_Contact_Ind")
    protected String directContactInd;
    @XmlElement(name = "Dialing_Cd")
    protected String dialingCd;
    @XmlElement(name = "Phone_Nr")
    protected String phoneNr;
    @XmlElement(name = "Bus_Hr_Cov_Rad")
    protected BigDecimal busHrCovRad;
    @XmlElement(name = "Non_Bus_Hr_Cov_Rad")
    protected BigDecimal nonBusHrCovRad;
    @XmlElement(name = "Bus_Hr_Area")
    protected String busHrArea;
    @XmlElement(name = "Ops_Area")
    protected String opsArea;
    @XmlElement(name = "Is_Active")
    protected String isActive;
    @XmlElement(name = "Is_Enabled")
    protected String isEnabled;

    /**
     * Gets the value of the supplierId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * Sets the value of the supplierId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSupplierId(Integer value) {
        this.supplierId = value;
    }

    /**
     * Gets the value of the msuSeqId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMsuSeqId() {
        return msuSeqId;
    }

    /**
     * Sets the value of the msuSeqId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMsuSeqId(Integer value) {
        this.msuSeqId = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGroupId(Integer value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the groupDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupDesc() {
        return groupDesc;
    }

    /**
     * Sets the value of the groupDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupDesc(String value) {
        this.groupDesc = value;
    }

    /**
     * Gets the value of the subGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSubGroupId() {
        return subGroupId;
    }

    /**
     * Sets the value of the subGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSubGroupId(Integer value) {
        this.subGroupId = value;
    }

    /**
     * Gets the value of the subGroupDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubGroupDesc() {
        return subGroupDesc;
    }

    /**
     * Sets the value of the subGroupDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubGroupDesc(String value) {
        this.subGroupDesc = value;
    }

    /**
     * Gets the value of the itemId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * Sets the value of the itemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setItemId(Integer value) {
        this.itemId = value;
    }

    /**
     * Gets the value of the itemDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * Sets the value of the itemDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemDesc(String value) {
        this.itemDesc = value;
    }

    /**
     * Gets the value of the regNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegNr() {
        return regNr;
    }

    /**
     * Sets the value of the regNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegNr(String value) {
        this.regNr = value;
    }

    /**
     * Gets the value of the fleetNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFleetNr() {
        return fleetNr;
    }

    /**
     * Sets the value of the fleetNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFleetNr(String value) {
        this.fleetNr = value;
    }

    /**
     * Gets the value of the directContactInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectContactInd() {
        return directContactInd;
    }

    /**
     * Sets the value of the directContactInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectContactInd(String value) {
        this.directContactInd = value;
    }

    /**
     * Gets the value of the dialingCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDialingCd() {
        return dialingCd;
    }

    /**
     * Sets the value of the dialingCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDialingCd(String value) {
        this.dialingCd = value;
    }

    /**
     * Gets the value of the phoneNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNr() {
        return phoneNr;
    }

    /**
     * Sets the value of the phoneNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNr(String value) {
        this.phoneNr = value;
    }

    /**
     * Gets the value of the busHrCovRad property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBusHrCovRad() {
        return busHrCovRad;
    }

    /**
     * Sets the value of the busHrCovRad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBusHrCovRad(BigDecimal value) {
        this.busHrCovRad = value;
    }

    /**
     * Gets the value of the nonBusHrCovRad property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNonBusHrCovRad() {
        return nonBusHrCovRad;
    }

    /**
     * Sets the value of the nonBusHrCovRad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNonBusHrCovRad(BigDecimal value) {
        this.nonBusHrCovRad = value;
    }

    /**
     * Gets the value of the busHrArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusHrArea() {
        return busHrArea;
    }

    /**
     * Sets the value of the busHrArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusHrArea(String value) {
        this.busHrArea = value;
    }

    /**
     * Gets the value of the opsArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpsArea() {
        return opsArea;
    }

    /**
     * Sets the value of the opsArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpsArea(String value) {
        this.opsArea = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsActive(String value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the isEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsEnabled() {
        return isEnabled;
    }

    /**
     * Sets the value of the isEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsEnabled(String value) {
        this.isEnabled = value;
    }

}
