//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.11 at 02:04:05 PM IST 
//


package com.tip.estimation.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EstnWorkOrderObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EstnWorkOrderObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="estnworkorderId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="groupCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="woCustComments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="woIntComments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="supplierId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="EstnWorkOrderTaskList" type="{http://www.example.org/SaveEstnWorkOrder}EstnWorkOrderTaskObject" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EstnWorkOrderObject", propOrder = {
    "estnworkorderId",
    "groupCd",
    "woCustComments",
    "woIntComments",
    "supplierId",
    "estnWorkOrderTaskList"
})
public class EstnWorkOrderObject {

    protected Integer estnworkorderId;
    protected String groupCd;
    protected String woCustComments;
    protected String woIntComments;
    protected Integer supplierId;
    @XmlElement(name = "EstnWorkOrderTaskList", required = true)
    protected List<EstnWorkOrderTaskObject> estnWorkOrderTaskList;

    /**
     * Gets the value of the estnworkorderId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEstnworkorderId() {
        return estnworkorderId;
    }

    /**
     * Sets the value of the estnworkorderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEstnworkorderId(Integer value) {
        this.estnworkorderId = value;
    }

    /**
     * Gets the value of the groupCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupCd() {
        return groupCd;
    }

    /**
     * Sets the value of the groupCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupCd(String value) {
        this.groupCd = value;
    }

    /**
     * Gets the value of the woCustComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWoCustComments() {
        return woCustComments;
    }

    /**
     * Sets the value of the woCustComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWoCustComments(String value) {
        this.woCustComments = value;
    }

    /**
     * Gets the value of the woIntComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWoIntComments() {
        return woIntComments;
    }

    /**
     * Sets the value of the woIntComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWoIntComments(String value) {
        this.woIntComments = value;
    }

    /**
     * Gets the value of the supplierId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * Sets the value of the supplierId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSupplierId(Integer value) {
        this.supplierId = value;
    }

    /**
     * Gets the value of the estnWorkOrderTaskList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estnWorkOrderTaskList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstnWorkOrderTaskList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstnWorkOrderTaskObject }
     * 
     * 
     */
    public List<EstnWorkOrderTaskObject> getEstnWorkOrderTaskList() {
        if (estnWorkOrderTaskList == null) {
            estnWorkOrderTaskList = new ArrayList<EstnWorkOrderTaskObject>();
        }
        return this.estnWorkOrderTaskList;
    }

}
