//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.04 at 07:57:08 PM IST 
//


package com.tip.estimation.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SaveEnrichDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SaveEnrichDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EstnHeaderList" type="{http://www.example.org/SaveEnrichDetails}EnrichHeaderObject" minOccurs="0"/>
 *         &lt;element name="EstnUnMatchedPartLists" type="{http://www.example.org/SaveEnrichDetails}EnrichPartsObject" maxOccurs="unbounded"/>
 *         &lt;element name="TyreSpeclist" type="{http://www.example.org/SaveEnrichDetails}EnrichTyreSpecsObject" maxOccurs="unbounded"/>
 *         &lt;element name="TyreServicelist" type="{http://www.example.org/SaveEnrichDetails}EnrichTyreServiceObject" maxOccurs="unbounded"/>
 *         &lt;element name="EstnBundleLists" type="{http://www.example.org/SaveEnrichDetails}BundleHeader" maxOccurs="unbounded"/>
 *         &lt;element name="EstnConsumablesDetails" type="{http://www.example.org/SaveEnrichDetails}EnrichConsumablesObject" maxOccurs="unbounded"/>
 *         &lt;element name="EstnFeeList" type="{http://www.example.org/SaveEnrichDetails}EnrichFeeObject" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SaveEnrichDetails", propOrder = {
    "estnHeaderList",
    "estnUnMatchedPartLists",
    "tyreSpeclist",
    "tyreServicelist",
    "estnBundleLists",
    "estnConsumablesDetails",
    "estnFeeList"
})
public class SaveEnrichDetails {

    @XmlElement(name = "EstnHeaderList")
    protected EnrichHeaderObject estnHeaderList;
    @XmlElement(name = "EstnUnMatchedPartLists", required = true)
    protected List<EnrichPartsObject> estnUnMatchedPartLists;
    @XmlElement(name = "TyreSpeclist", required = true)
    protected List<EnrichTyreSpecsObject> tyreSpeclist;
    @XmlElement(name = "TyreServicelist", required = true)
    protected List<EnrichTyreServiceObject> tyreServicelist;
    @XmlElement(name = "EstnBundleLists", required = true)
    protected List<BundleHeader> estnBundleLists;
    @XmlElement(name = "EstnConsumablesDetails", required = true)
    protected List<EnrichConsumablesObject> estnConsumablesDetails;
    @XmlElement(name = "EstnFeeList", required = true)
    protected List<EnrichFeeObject> estnFeeList;

    /**
     * Gets the value of the estnHeaderList property.
     * 
     * @return
     *     possible object is
     *     {@link EnrichHeaderObject }
     *     
     */
    public EnrichHeaderObject getEstnHeaderList() {
        return estnHeaderList;
    }

    /**
     * Sets the value of the estnHeaderList property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnrichHeaderObject }
     *     
     */
    public void setEstnHeaderList(EnrichHeaderObject value) {
        this.estnHeaderList = value;
    }

    /**
     * Gets the value of the estnUnMatchedPartLists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estnUnMatchedPartLists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstnUnMatchedPartLists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnrichPartsObject }
     * 
     * 
     */
    public List<EnrichPartsObject> getEstnUnMatchedPartLists() {
        if (estnUnMatchedPartLists == null) {
            estnUnMatchedPartLists = new ArrayList<EnrichPartsObject>();
        }
        return this.estnUnMatchedPartLists;
    }

    /**
     * Gets the value of the tyreSpeclist property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tyreSpeclist property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTyreSpeclist().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnrichTyreSpecsObject }
     * 
     * 
     */
    public List<EnrichTyreSpecsObject> getTyreSpeclist() {
        if (tyreSpeclist == null) {
            tyreSpeclist = new ArrayList<EnrichTyreSpecsObject>();
        }
        return this.tyreSpeclist;
    }

    /**
     * Gets the value of the tyreServicelist property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tyreServicelist property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTyreServicelist().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnrichTyreServiceObject }
     * 
     * 
     */
    public List<EnrichTyreServiceObject> getTyreServicelist() {
        if (tyreServicelist == null) {
            tyreServicelist = new ArrayList<EnrichTyreServiceObject>();
        }
        return this.tyreServicelist;
    }

    /**
     * Gets the value of the estnBundleLists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estnBundleLists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstnBundleLists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BundleHeader }
     * 
     * 
     */
    public List<BundleHeader> getEstnBundleLists() {
        if (estnBundleLists == null) {
            estnBundleLists = new ArrayList<BundleHeader>();
        }
        return this.estnBundleLists;
    }

    /**
     * Gets the value of the estnConsumablesDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estnConsumablesDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstnConsumablesDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnrichConsumablesObject }
     * 
     * 
     */
    public List<EnrichConsumablesObject> getEstnConsumablesDetails() {
        if (estnConsumablesDetails == null) {
            estnConsumablesDetails = new ArrayList<EnrichConsumablesObject>();
        }
        return this.estnConsumablesDetails;
    }

    /**
     * Gets the value of the estnFeeList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estnFeeList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstnFeeList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnrichFeeObject }
     * 
     * 
     */
    public List<EnrichFeeObject> getEstnFeeList() {
        if (estnFeeList == null) {
            estnFeeList = new ArrayList<EnrichFeeObject>();
        }
        return this.estnFeeList;
    }

}
