//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.21 at 04:26:11 PM IST 
//


package com.tip.estimation.model;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SaveEstnOtherReadingRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SaveEstnOtherReadingRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="estimationId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="hubReading" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="electricHours" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="deiselHours" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="fuel" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="loaded" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fuelCapaicty" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="fuelMeterBroken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="operatorName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="noHubodometer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hubodometerBroken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="motDocDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fridgeManufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fridgeModel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fridgeSerialNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="monthOfManufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="yearOfManufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pressureTestDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tailliftManufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tailliftModel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tailliftSerialNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ssoId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SaveEstnOtherReadingRequest", propOrder = {
    "estimationId",
    "hubReading",
    "electricHours",
    "deiselHours",
    "fuel",
    "loaded",
    "fuelCapaicty",
    "fuelMeterBroken",
    "operatorName",
    "noHubodometer",
    "hubodometerBroken",
    "motDocDate",
    "fridgeManufacturer",
    "fridgeModel",
    "fridgeSerialNr",
    "monthOfManufacturer",
    "yearOfManufacturer",
    "pressureTestDate",
    "tailliftManufacturer",
    "tailliftModel",
    "tailliftSerialNr",
    "ssoId"
})
public class SaveEstnOtherReadingRequest {

    protected BigDecimal estimationId;
    protected Integer hubReading;
    protected Integer electricHours;
    protected Integer deiselHours;
    protected Float fuel;
    protected String loaded;
    protected Float fuelCapaicty;
    protected String fuelMeterBroken;
    protected String operatorName;
    protected String noHubodometer;
    protected String hubodometerBroken;
    protected String motDocDate;
    protected String fridgeManufacturer;
    protected String fridgeModel;
    protected String fridgeSerialNr;
    protected String monthOfManufacturer;
    protected Integer yearOfManufacturer;
    protected String pressureTestDate;
    protected String tailliftManufacturer;
    protected String tailliftModel;
    protected String tailliftSerialNr;
    protected String ssoId;

    /**
     * Gets the value of the estimationId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEstimationId() {
        return estimationId;
    }

    /**
     * Sets the value of the estimationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEstimationId(BigDecimal value) {
        this.estimationId = value;
    }

    /**
     * Gets the value of the hubReading property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHubReading() {
        return hubReading;
    }

    /**
     * Sets the value of the hubReading property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHubReading(Integer value) {
        this.hubReading = value;
    }

    /**
     * Gets the value of the electricHours property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getElectricHours() {
        return electricHours;
    }

    /**
     * Sets the value of the electricHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setElectricHours(Integer value) {
        this.electricHours = value;
    }

    /**
     * Gets the value of the deiselHours property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDeiselHours() {
        return deiselHours;
    }

    /**
     * Sets the value of the deiselHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDeiselHours(Integer value) {
        this.deiselHours = value;
    }

    /**
     * Gets the value of the fuel property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFuel() {
        return fuel;
    }

    /**
     * Sets the value of the fuel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFuel(Float value) {
        this.fuel = value;
    }

    /**
     * Gets the value of the loaded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoaded() {
        return loaded;
    }

    /**
     * Sets the value of the loaded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoaded(String value) {
        this.loaded = value;
    }

    /**
     * Gets the value of the fuelCapaicty property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFuelCapaicty() {
        return fuelCapaicty;
    }

    /**
     * Sets the value of the fuelCapaicty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFuelCapaicty(Float value) {
        this.fuelCapaicty = value;
    }

    /**
     * Gets the value of the fuelMeterBroken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuelMeterBroken() {
        return fuelMeterBroken;
    }

    /**
     * Sets the value of the fuelMeterBroken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuelMeterBroken(String value) {
        this.fuelMeterBroken = value;
    }

    /**
     * Gets the value of the operatorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * Sets the value of the operatorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatorName(String value) {
        this.operatorName = value;
    }

    /**
     * Gets the value of the noHubodometer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoHubodometer() {
        return noHubodometer;
    }

    /**
     * Sets the value of the noHubodometer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoHubodometer(String value) {
        this.noHubodometer = value;
    }

    /**
     * Gets the value of the hubodometerBroken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHubodometerBroken() {
        return hubodometerBroken;
    }

    /**
     * Sets the value of the hubodometerBroken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHubodometerBroken(String value) {
        this.hubodometerBroken = value;
    }

    /**
     * Gets the value of the motDocDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotDocDate() {
        return motDocDate;
    }

    /**
     * Sets the value of the motDocDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotDocDate(String value) {
        this.motDocDate = value;
    }

    /**
     * Gets the value of the fridgeManufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFridgeManufacturer() {
        return fridgeManufacturer;
    }

    /**
     * Sets the value of the fridgeManufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFridgeManufacturer(String value) {
        this.fridgeManufacturer = value;
    }

    /**
     * Gets the value of the fridgeModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFridgeModel() {
        return fridgeModel;
    }

    /**
     * Sets the value of the fridgeModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFridgeModel(String value) {
        this.fridgeModel = value;
    }

    /**
     * Gets the value of the fridgeSerialNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFridgeSerialNr() {
        return fridgeSerialNr;
    }

    /**
     * Sets the value of the fridgeSerialNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFridgeSerialNr(String value) {
        this.fridgeSerialNr = value;
    }

    /**
     * Gets the value of the monthOfManufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonthOfManufacturer() {
        return monthOfManufacturer;
    }

    /**
     * Sets the value of the monthOfManufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonthOfManufacturer(String value) {
        this.monthOfManufacturer = value;
    }

    /**
     * Gets the value of the yearOfManufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getYearOfManufacturer() {
        return yearOfManufacturer;
    }

    /**
     * Sets the value of the yearOfManufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYearOfManufacturer(Integer value) {
        this.yearOfManufacturer = value;
    }

    /**
     * Gets the value of the pressureTestDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPressureTestDate() {
        return pressureTestDate;
    }

    /**
     * Sets the value of the pressureTestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPressureTestDate(String value) {
        this.pressureTestDate = value;
    }

    /**
     * Gets the value of the tailliftManufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTailliftManufacturer() {
        return tailliftManufacturer;
    }

    /**
     * Sets the value of the tailliftManufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTailliftManufacturer(String value) {
        this.tailliftManufacturer = value;
    }

    /**
     * Gets the value of the tailliftModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTailliftModel() {
        return tailliftModel;
    }

    /**
     * Sets the value of the tailliftModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTailliftModel(String value) {
        this.tailliftModel = value;
    }

    /**
     * Gets the value of the tailliftSerialNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTailliftSerialNr() {
        return tailliftSerialNr;
    }

    /**
     * Sets the value of the tailliftSerialNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTailliftSerialNr(String value) {
        this.tailliftSerialNr = value;
    }

    /**
     * Gets the value of the ssoId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsoId() {
        return ssoId;
    }

    /**
     * Sets the value of the ssoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsoId(String value) {
        this.ssoId = value;
    }

}
