//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.21 at 07:17:58 PM IST 
//


package com.tip.estimation.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SaveEstnTyreRdngRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SaveEstnTyreRdngRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EstnTyreReadingList" type="{http://www.example.org/SaveEstnTyreReadings}EstnTyreReadingObject" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SaveEstnTyreRdngRequest", propOrder = {
    "estnTyreReadingList"
})
public class SaveEstnTyreRdngRequest {

    @XmlElement(name = "EstnTyreReadingList", required = true)
    protected List<EstnTyreReadingObject> estnTyreReadingList;

    /**
     * Gets the value of the estnTyreReadingList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estnTyreReadingList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstnTyreReadingList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstnTyreReadingObject }
     * 
     * 
     */
    public List<EstnTyreReadingObject> getEstnTyreReadingList() {
        if (estnTyreReadingList == null) {
            estnTyreReadingList = new ArrayList<EstnTyreReadingObject>();
        }
        return this.estnTyreReadingList;
    }

}
