//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.20 at 08:49:15 PM IST 
//


package com.tip.fetchinspectionreport.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InspTranslationObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InspTranslationObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HtrailerNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HregNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HserviceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hchassis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hmileage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HmotDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hjobdate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HjobShtNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hoperator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hserviceable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hdefect" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hna" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HinspA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hbrake" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hchassis_Susp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Helectric" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hsuperstructure" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HaxlesTyre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hother" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HinspB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HaddInspB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HinspC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HaddInspC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hinspector" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hdate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hroadworthy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hsigned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hnr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hdefects" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hactions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HactionBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Htyrereadings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hbrakereadings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hfaxis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hcaxis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hraxis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hmm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hpsi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InspTranslationObject", propOrder = {
    "htrailerNr",
    "hregNr",
    "hserviceType",
    "hchassis",
    "hmileage",
    "hmotDate",
    "hjobdate",
    "hjobShtNr",
    "hoperator",
    "hserviceable",
    "hdefect",
    "hna",
    "hinspA",
    "hbrake",
    "hchassisSusp",
    "helectric",
    "hsuperstructure",
    "haxlesTyre",
    "hother",
    "hinspB",
    "haddInspB",
    "hinspC",
    "haddInspC",
    "hinspector",
    "hdate",
    "hroadworthy",
    "hsigned",
    "hnr",
    "hdefects",
    "hactions",
    "hactionBy",
    "htyrereadings",
    "hbrakereadings",
    "hfaxis",
    "hcaxis",
    "hraxis",
    "hmm",
    "hpsi"
})
public class InspTranslationObject {

    @XmlElement(name = "HtrailerNr")
    protected String htrailerNr;
    @XmlElement(name = "HregNr")
    protected String hregNr;
    @XmlElement(name = "HserviceType")
    protected String hserviceType;
    @XmlElement(name = "Hchassis")
    protected String hchassis;
    @XmlElement(name = "Hmileage")
    protected String hmileage;
    @XmlElement(name = "HmotDate")
    protected String hmotDate;
    @XmlElement(name = "Hjobdate")
    protected String hjobdate;
    @XmlElement(name = "HjobShtNr")
    protected String hjobShtNr;
    @XmlElement(name = "Hoperator")
    protected String hoperator;
    @XmlElement(name = "Hserviceable")
    protected String hserviceable;
    @XmlElement(name = "Hdefect")
    protected String hdefect;
    @XmlElement(name = "Hna")
    protected String hna;
    @XmlElement(name = "HinspA")
    protected String hinspA;
    @XmlElement(name = "Hbrake")
    protected String hbrake;
    @XmlElement(name = "Hchassis_Susp")
    protected String hchassisSusp;
    @XmlElement(name = "Helectric")
    protected String helectric;
    @XmlElement(name = "Hsuperstructure")
    protected String hsuperstructure;
    @XmlElement(name = "HaxlesTyre")
    protected String haxlesTyre;
    @XmlElement(name = "Hother")
    protected String hother;
    @XmlElement(name = "HinspB")
    protected String hinspB;
    @XmlElement(name = "HaddInspB")
    protected String haddInspB;
    @XmlElement(name = "HinspC")
    protected String hinspC;
    @XmlElement(name = "HaddInspC")
    protected String haddInspC;
    @XmlElement(name = "Hinspector")
    protected String hinspector;
    @XmlElement(name = "Hdate")
    protected String hdate;
    @XmlElement(name = "Hroadworthy")
    protected String hroadworthy;
    @XmlElement(name = "Hsigned")
    protected String hsigned;
    @XmlElement(name = "Hnr")
    protected String hnr;
    @XmlElement(name = "Hdefects")
    protected String hdefects;
    @XmlElement(name = "Hactions")
    protected String hactions;
    @XmlElement(name = "HactionBy")
    protected String hactionBy;
    @XmlElement(name = "Htyrereadings")
    protected String htyrereadings;
    @XmlElement(name = "Hbrakereadings")
    protected String hbrakereadings;
    @XmlElement(name = "Hfaxis")
    protected String hfaxis;
    @XmlElement(name = "Hcaxis")
    protected String hcaxis;
    @XmlElement(name = "Hraxis")
    protected String hraxis;
    @XmlElement(name = "Hmm")
    protected String hmm;
    @XmlElement(name = "Hpsi")
    protected String hpsi;

    /**
     * Gets the value of the htrailerNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtrailerNr() {
        return htrailerNr;
    }

    /**
     * Sets the value of the htrailerNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtrailerNr(String value) {
        this.htrailerNr = value;
    }

    /**
     * Gets the value of the hregNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHregNr() {
        return hregNr;
    }

    /**
     * Sets the value of the hregNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHregNr(String value) {
        this.hregNr = value;
    }

    /**
     * Gets the value of the hserviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHserviceType() {
        return hserviceType;
    }

    /**
     * Sets the value of the hserviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHserviceType(String value) {
        this.hserviceType = value;
    }

    /**
     * Gets the value of the hchassis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHchassis() {
        return hchassis;
    }

    /**
     * Sets the value of the hchassis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHchassis(String value) {
        this.hchassis = value;
    }

    /**
     * Gets the value of the hmileage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHmileage() {
        return hmileage;
    }

    /**
     * Sets the value of the hmileage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHmileage(String value) {
        this.hmileage = value;
    }

    /**
     * Gets the value of the hmotDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHmotDate() {
        return hmotDate;
    }

    /**
     * Sets the value of the hmotDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHmotDate(String value) {
        this.hmotDate = value;
    }

    /**
     * Gets the value of the hjobdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHjobdate() {
        return hjobdate;
    }

    /**
     * Sets the value of the hjobdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHjobdate(String value) {
        this.hjobdate = value;
    }

    /**
     * Gets the value of the hjobShtNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHjobShtNr() {
        return hjobShtNr;
    }

    /**
     * Sets the value of the hjobShtNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHjobShtNr(String value) {
        this.hjobShtNr = value;
    }

    /**
     * Gets the value of the hoperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoperator() {
        return hoperator;
    }

    /**
     * Sets the value of the hoperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoperator(String value) {
        this.hoperator = value;
    }

    /**
     * Gets the value of the hserviceable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHserviceable() {
        return hserviceable;
    }

    /**
     * Sets the value of the hserviceable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHserviceable(String value) {
        this.hserviceable = value;
    }

    /**
     * Gets the value of the hdefect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdefect() {
        return hdefect;
    }

    /**
     * Sets the value of the hdefect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdefect(String value) {
        this.hdefect = value;
    }

    /**
     * Gets the value of the hna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHna() {
        return hna;
    }

    /**
     * Sets the value of the hna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHna(String value) {
        this.hna = value;
    }

    /**
     * Gets the value of the hinspA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHinspA() {
        return hinspA;
    }

    /**
     * Sets the value of the hinspA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHinspA(String value) {
        this.hinspA = value;
    }

    /**
     * Gets the value of the hbrake property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHbrake() {
        return hbrake;
    }

    /**
     * Sets the value of the hbrake property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHbrake(String value) {
        this.hbrake = value;
    }

    /**
     * Gets the value of the hchassisSusp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHchassisSusp() {
        return hchassisSusp;
    }

    /**
     * Sets the value of the hchassisSusp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHchassisSusp(String value) {
        this.hchassisSusp = value;
    }

    /**
     * Gets the value of the helectric property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelectric() {
        return helectric;
    }

    /**
     * Sets the value of the helectric property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelectric(String value) {
        this.helectric = value;
    }

    /**
     * Gets the value of the hsuperstructure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHsuperstructure() {
        return hsuperstructure;
    }

    /**
     * Sets the value of the hsuperstructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHsuperstructure(String value) {
        this.hsuperstructure = value;
    }

    /**
     * Gets the value of the haxlesTyre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHaxlesTyre() {
        return haxlesTyre;
    }

    /**
     * Sets the value of the haxlesTyre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHaxlesTyre(String value) {
        this.haxlesTyre = value;
    }

    /**
     * Gets the value of the hother property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHother() {
        return hother;
    }

    /**
     * Sets the value of the hother property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHother(String value) {
        this.hother = value;
    }

    /**
     * Gets the value of the hinspB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHinspB() {
        return hinspB;
    }

    /**
     * Sets the value of the hinspB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHinspB(String value) {
        this.hinspB = value;
    }

    /**
     * Gets the value of the haddInspB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHaddInspB() {
        return haddInspB;
    }

    /**
     * Sets the value of the haddInspB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHaddInspB(String value) {
        this.haddInspB = value;
    }

    /**
     * Gets the value of the hinspC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHinspC() {
        return hinspC;
    }

    /**
     * Sets the value of the hinspC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHinspC(String value) {
        this.hinspC = value;
    }

    /**
     * Gets the value of the haddInspC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHaddInspC() {
        return haddInspC;
    }

    /**
     * Sets the value of the haddInspC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHaddInspC(String value) {
        this.haddInspC = value;
    }

    /**
     * Gets the value of the hinspector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHinspector() {
        return hinspector;
    }

    /**
     * Sets the value of the hinspector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHinspector(String value) {
        this.hinspector = value;
    }

    /**
     * Gets the value of the hdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdate() {
        return hdate;
    }

    /**
     * Sets the value of the hdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdate(String value) {
        this.hdate = value;
    }

    /**
     * Gets the value of the hroadworthy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHroadworthy() {
        return hroadworthy;
    }

    /**
     * Sets the value of the hroadworthy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHroadworthy(String value) {
        this.hroadworthy = value;
    }

    /**
     * Gets the value of the hsigned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHsigned() {
        return hsigned;
    }

    /**
     * Sets the value of the hsigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHsigned(String value) {
        this.hsigned = value;
    }

    /**
     * Gets the value of the hnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHnr() {
        return hnr;
    }

    /**
     * Sets the value of the hnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHnr(String value) {
        this.hnr = value;
    }

    /**
     * Gets the value of the hdefects property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdefects() {
        return hdefects;
    }

    /**
     * Sets the value of the hdefects property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdefects(String value) {
        this.hdefects = value;
    }

    /**
     * Gets the value of the hactions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHactions() {
        return hactions;
    }

    /**
     * Sets the value of the hactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHactions(String value) {
        this.hactions = value;
    }

    /**
     * Gets the value of the hactionBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHactionBy() {
        return hactionBy;
    }

    /**
     * Sets the value of the hactionBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHactionBy(String value) {
        this.hactionBy = value;
    }

    /**
     * Gets the value of the htyrereadings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtyrereadings() {
        return htyrereadings;
    }

    /**
     * Sets the value of the htyrereadings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtyrereadings(String value) {
        this.htyrereadings = value;
    }

    /**
     * Gets the value of the hbrakereadings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHbrakereadings() {
        return hbrakereadings;
    }

    /**
     * Sets the value of the hbrakereadings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHbrakereadings(String value) {
        this.hbrakereadings = value;
    }

    /**
     * Gets the value of the hfaxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHfaxis() {
        return hfaxis;
    }

    /**
     * Sets the value of the hfaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHfaxis(String value) {
        this.hfaxis = value;
    }

    /**
     * Gets the value of the hcaxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHcaxis() {
        return hcaxis;
    }

    /**
     * Sets the value of the hcaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHcaxis(String value) {
        this.hcaxis = value;
    }

    /**
     * Gets the value of the hraxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHraxis() {
        return hraxis;
    }

    /**
     * Sets the value of the hraxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHraxis(String value) {
        this.hraxis = value;
    }

    /**
     * Gets the value of the hmm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHmm() {
        return hmm;
    }

    /**
     * Sets the value of the hmm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHmm(String value) {
        this.hmm = value;
    }

    /**
     * Gets the value of the hpsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHpsi() {
        return hpsi;
    }

    /**
     * Sets the value of the hpsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHpsi(String value) {
        this.hpsi = value;
    }

}
