//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.20 at 08:49:15 PM IST 
//


package com.tip.fetchinspectionreport.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InspHeaderObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InspHeaderObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TrailerNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegistrationNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ServiceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Chassis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Mileage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MotDueDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="JobDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="JobSheetNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Operator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RoadWorthy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InspHeaderObject", propOrder = {
    "trailerNr",
    "registrationNr",
    "serviceType",
    "chassis",
    "mileage",
    "motDueDate",
    "jobDate",
    "jobSheetNr",
    "operator",
    "roadWorthy"
})
public class InspHeaderObject {

    @XmlElement(name = "TrailerNr")
    protected String trailerNr;
    @XmlElement(name = "RegistrationNr")
    protected String registrationNr;
    @XmlElement(name = "ServiceType")
    protected String serviceType;
    @XmlElement(name = "Chassis")
    protected String chassis;
    @XmlElement(name = "Mileage")
    protected String mileage;
    @XmlElement(name = "MotDueDate")
    protected String motDueDate;
    @XmlElement(name = "JobDate")
    protected String jobDate;
    @XmlElement(name = "JobSheetNr")
    protected String jobSheetNr;
    @XmlElement(name = "Operator")
    protected String operator;
    @XmlElement(name = "RoadWorthy")
    protected String roadWorthy;

    /**
     * Gets the value of the trailerNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrailerNr() {
        return trailerNr;
    }

    /**
     * Sets the value of the trailerNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrailerNr(String value) {
        this.trailerNr = value;
    }

    /**
     * Gets the value of the registrationNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationNr() {
        return registrationNr;
    }

    /**
     * Sets the value of the registrationNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationNr(String value) {
        this.registrationNr = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the chassis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChassis() {
        return chassis;
    }

    /**
     * Sets the value of the chassis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChassis(String value) {
        this.chassis = value;
    }

    /**
     * Gets the value of the mileage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMileage() {
        return mileage;
    }

    /**
     * Sets the value of the mileage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMileage(String value) {
        this.mileage = value;
    }

    /**
     * Gets the value of the motDueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotDueDate() {
        return motDueDate;
    }

    /**
     * Sets the value of the motDueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotDueDate(String value) {
        this.motDueDate = value;
    }

    /**
     * Gets the value of the jobDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobDate() {
        return jobDate;
    }

    /**
     * Sets the value of the jobDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobDate(String value) {
        this.jobDate = value;
    }

    /**
     * Gets the value of the jobSheetNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobSheetNr() {
        return jobSheetNr;
    }

    /**
     * Sets the value of the jobSheetNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobSheetNr(String value) {
        this.jobSheetNr = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperator(String value) {
        this.operator = value;
    }

    /**
     * Gets the value of the roadWorthy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoadWorthy() {
        return roadWorthy;
    }

    /**
     * Sets the value of the roadWorthy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoadWorthy(String value) {
        this.roadWorthy = value;
    }

}
