//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.01 at 09:11:15 PM IST 
//


package com.tip.fetchdynamicmasterdata.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EquipmentTypes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EquipmentTypes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="catgr_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="catgr_desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="catgr_level" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="catgr_of" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="catgr_shortn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="catgr_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EquipmentTypes", propOrder = {
    "catgrId",
    "catgrDesc",
    "catgrLevel",
    "catgrOf",
    "catgrShortn",
    "catgrCode"
})
public class EquipmentTypes {

    @XmlElement(name = "catgr_id")
    protected String catgrId;
    @XmlElement(name = "catgr_desc")
    protected String catgrDesc;
    @XmlElement(name = "catgr_level")
    protected String catgrLevel;
    @XmlElement(name = "catgr_of")
    protected Integer catgrOf;
    @XmlElement(name = "catgr_shortn")
    protected String catgrShortn;
    @XmlElement(name = "catgr_code")
    protected String catgrCode;

    /**
     * Gets the value of the catgrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatgrId() {
        return catgrId;
    }

    /**
     * Sets the value of the catgrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatgrId(String value) {
        this.catgrId = value;
    }

    /**
     * Gets the value of the catgrDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatgrDesc() {
        return catgrDesc;
    }

    /**
     * Sets the value of the catgrDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatgrDesc(String value) {
        this.catgrDesc = value;
    }

    /**
     * Gets the value of the catgrLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatgrLevel() {
        return catgrLevel;
    }

    /**
     * Sets the value of the catgrLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatgrLevel(String value) {
        this.catgrLevel = value;
    }

    /**
     * Gets the value of the catgrOf property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCatgrOf() {
        return catgrOf;
    }

    /**
     * Sets the value of the catgrOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCatgrOf(Integer value) {
        this.catgrOf = value;
    }

    /**
     * Gets the value of the catgrShortn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatgrShortn() {
        return catgrShortn;
    }

    /**
     * Sets the value of the catgrShortn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatgrShortn(String value) {
        this.catgrShortn = value;
    }

    /**
     * Gets the value of the catgrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatgrCode() {
        return catgrCode;
    }

    /**
     * Sets the value of the catgrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatgrCode(String value) {
        this.catgrCode = value;
    }

}
