//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 12:49:53 PM IST 
//


package com.tip.customer.model;

import java.math.BigDecimal;

public class CustomerData {

    protected Integer customerSkey;
    protected Integer customerNr;
    protected Integer customerNumberCombi;
    protected String customerNameAbbreviation;
    protected String customerName;
    protected String name;
    protected String upperName;
    protected String sfdcExternalAccountId;
    protected String customerRegistrationNr;
    
    protected Integer customerSalesPhone;
    protected Integer customerCollectionPhone;
    protected String customerOperationsPostalCd;
    protected String customerInvoicePostalCd;
    protected String customerStreetAddr;
    protected String customerCity;
    protected String customerAlfaNr;
    protected String phoneNumber;
    protected String addr;
    protected String city;
    protected String zipCd;
    protected String upperCity;
    protected String emailAddress;
    
    protected Integer aaCountrySkey ;
    protected String aaNote;
    protected String countryDialingCd;
    protected String vatNumber;
    protected String customerLanguageCd;
    protected Integer customerCompanyNr;
    protected Integer customerBranchNr;
    protected Integer customerBillingCompanyNr;
    protected Integer customerBillingBranchNr;
    protected Integer customerOriginalBranchNr;
    protected String customerAddedDate;
    protected String customerCountryCd;
    protected String customerStatusCd;
    protected Integer phoneSkey;
    protected Integer entityId;
    protected String entityType;
    protected Integer phoneTypeRef;
    protected Integer seq;
    protected Integer countrySkey;
    protected Integer addressSkey;
    protected String aaEntityType;
    protected Integer aaEntityId;
    protected Integer addressTypeRef;
    protected Integer aaSeq;
    protected Integer statusRef;
    protected Integer companyTypeRef;
    protected Integer dataPrivacyId;
    protected String sfdcInternalAccountId;
    protected String taxExemptReasonCd;
	public Integer getCustomerSkey() {
		return customerSkey;
	}
	public void setCustomerSkey(Integer customerSkey) {
		this.customerSkey = customerSkey;
	}
	public Integer getCustomerNr() {
		return customerNr;
	}
	public void setCustomerNr(Integer customerNr) {
		this.customerNr = customerNr;
	}
	public Integer getCustomerNumberCombi() {
		return customerNumberCombi;
	}
	public void setCustomerNumberCombi(Integer customerNumberCombi) {
		this.customerNumberCombi = customerNumberCombi;
	}
	public String getCustomerNameAbbreviation() {
		return customerNameAbbreviation;
	}
	public void setCustomerNameAbbreviation(String customerNameAbbreviation) {
		this.customerNameAbbreviation = customerNameAbbreviation;
	}
	public String getCustomerName() {
		return customerName;
	}
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getUpperName() {
		return upperName;
	}
	public void setUpperName(String upperName) {
		this.upperName = upperName;
	}
	public String getSfdcExternalAccountId() {
		return sfdcExternalAccountId;
	}
	public void setSfdcExternalAccountId(String sfdcExternalAccountId) {
		this.sfdcExternalAccountId = sfdcExternalAccountId;
	}
	public String getCustomerRegistrationNr() {
		return customerRegistrationNr;
	}
	public void setCustomerRegistrationNr(String customerRegistrationNr) {
		this.customerRegistrationNr = customerRegistrationNr;
	}
	public Integer getCustomerSalesPhone() {
		return customerSalesPhone;
	}
	public void setCustomerSalesPhone(Integer customerSalesPhone) {
		this.customerSalesPhone = customerSalesPhone;
	}
	public Integer getCustomerCollectionPhone() {
		return customerCollectionPhone;
	}
	public void setCustomerCollectionPhone(Integer customerCollectionPhone) {
		this.customerCollectionPhone = customerCollectionPhone;
	}
	public String getCustomerOperationsPostalCd() {
		return customerOperationsPostalCd;
	}
	public void setCustomerOperationsPostalCd(String customerOperationsPostalCd) {
		this.customerOperationsPostalCd = customerOperationsPostalCd;
	}
	public String getCustomerInvoicePostalCd() {
		return customerInvoicePostalCd;
	}
	public void setCustomerInvoicePostalCd(String customerInvoicePostalCd) {
		this.customerInvoicePostalCd = customerInvoicePostalCd;
	}
	public String getCustomerStreetAddr() {
		return customerStreetAddr;
	}
	public void setCustomerStreetAddr(String customerStreetAddr) {
		this.customerStreetAddr = customerStreetAddr;
	}
	public String getCustomerCity() {
		return customerCity;
	}
	public void setCustomerCity(String customerCity) {
		this.customerCity = customerCity;
	}
	public String getCustomerAlfaNr() {
		return customerAlfaNr;
	}
	public void setCustomerAlfaNr(String customerAlfaNr) {
		this.customerAlfaNr = customerAlfaNr;
	}
	public String getPhoneNumber() {
		return phoneNumber;
	}
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	public String getAddr() {
		return addr;
	}
	public void setAddr(String addr) {
		this.addr = addr;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public String getZipCd() {
		return zipCd;
	}
	public void setZipCd(String zipCd) {
		this.zipCd = zipCd;
	}
	public String getUpperCity() {
		return upperCity;
	}
	public void setUpperCity(String upperCity) {
		this.upperCity = upperCity;
	}
	public String getEmailAddress() {
		return emailAddress;
	}
	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}
	public Integer getAaCountrySkey() {
		return aaCountrySkey;
	}
	public void setAaCountrySkey(Integer aaCountrySkey) {
		this.aaCountrySkey = aaCountrySkey;
	}
	public String getAaNote() {
		return aaNote;
	}
	public void setAaNote(String aaNote) {
		this.aaNote = aaNote;
	}
	public String getCountryDialingCd() {
		return countryDialingCd;
	}
	public void setCountryDialingCd(String countryDialingCd) {
		this.countryDialingCd = countryDialingCd;
	}
	public String getVatNumber() {
		return vatNumber;
	}
	public void setVatNumber(String vatNumber) {
		this.vatNumber = vatNumber;
	}
	public String getCustomerLanguageCd() {
		return customerLanguageCd;
	}
	public void setCustomerLanguageCd(String customerLanguageCd) {
		this.customerLanguageCd = customerLanguageCd;
	}
	public Integer getCustomerCompanyNr() {
		return customerCompanyNr;
	}
	public void setCustomerCompanyNr(Integer customerCompanyNr) {
		this.customerCompanyNr = customerCompanyNr;
	}
	public Integer getCustomerBranchNr() {
		return customerBranchNr;
	}
	public void setCustomerBranchNr(Integer customerBranchNr) {
		this.customerBranchNr = customerBranchNr;
	}
	public Integer getCustomerBillingCompanyNr() {
		return customerBillingCompanyNr;
	}
	public void setCustomerBillingCompanyNr(Integer customerBillingCompanyNr) {
		this.customerBillingCompanyNr = customerBillingCompanyNr;
	}
	public Integer getCustomerBillingBranchNr() {
		return customerBillingBranchNr;
	}
	public void setCustomerBillingBranchNr(Integer customerBillingBranchNr) {
		this.customerBillingBranchNr = customerBillingBranchNr;
	}
	public Integer getCustomerOriginalBranchNr() {
		return customerOriginalBranchNr;
	}
	public void setCustomerOriginalBranchNr(Integer customerOriginalBranchNr) {
		this.customerOriginalBranchNr = customerOriginalBranchNr;
	}
	public String getCustomerAddedDate() {
		return customerAddedDate;
	}
	public void setCustomerAddedDate(String customerAddedDate) {
		this.customerAddedDate = customerAddedDate;
	}
	public String getCustomerCountryCd() {
		return customerCountryCd;
	}
	public void setCustomerCountryCd(String customerCountryCd) {
		this.customerCountryCd = customerCountryCd;
	}
	public String getCustomerStatusCd() {
		return customerStatusCd;
	}
	public void setCustomerStatusCd(String customerStatusCd) {
		this.customerStatusCd = customerStatusCd;
	}
	public Integer getPhoneSkey() {
		return phoneSkey;
	}
	public void setPhoneSkey(Integer phoneSkey) {
		this.phoneSkey = phoneSkey;
	}
	public Integer getEntityId() {
		return entityId;
	}
	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}
	public String getEntityType() {
		return entityType;
	}
	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}
	public Integer getPhoneTypeRef() {
		return phoneTypeRef;
	}
	public void setPhoneTypeRef(Integer phoneTypeRef) {
		this.phoneTypeRef = phoneTypeRef;
	}
	public Integer getSeq() {
		return seq;
	}
	public void setSeq(Integer seq) {
		this.seq = seq;
	}
	public Integer getCountrySkey() {
		return countrySkey;
	}
	public void setCountrySkey(Integer countrySkey) {
		this.countrySkey = countrySkey;
	}
	public Integer getAddressSkey() {
		return addressSkey;
	}
	public void setAddressSkey(Integer addressSkey) {
		this.addressSkey = addressSkey;
	}
	public String getAaEntityType() {
		return aaEntityType;
	}
	public void setAaEntityType(String aaEntityType) {
		this.aaEntityType = aaEntityType;
	}
	public Integer getAaEntityId() {
		return aaEntityId;
	}
	public void setAaEntityId(Integer aaEntityId) {
		this.aaEntityId = aaEntityId;
	}
	public Integer getAddressTypeRef() {
		return addressTypeRef;
	}
	public void setAddressTypeRef(Integer addressTypeRef) {
		this.addressTypeRef = addressTypeRef;
	}
	public Integer getAaSeq() {
		return aaSeq;
	}
	public void setAaSeq(Integer aaSeq) {
		this.aaSeq = aaSeq;
	}
	public Integer getStatusRef() {
		return statusRef;
	}
	public void setStatusRef(Integer statusRef) {
		this.statusRef = statusRef;
	}
	public Integer getCompanyTypeRef() {
		return companyTypeRef;
	}
	public void setCompanyTypeRef(Integer companyTypeRef) {
		this.companyTypeRef = companyTypeRef;
	}
	public Integer getDataPrivacyId() {
		return dataPrivacyId;
	}
	public void setDataPrivacyId(Integer dataPrivacyId) {
		this.dataPrivacyId = dataPrivacyId;
	}
	public String getSfdcInternalAccountId() {
		return sfdcInternalAccountId;
	}
	public void setSfdcInternalAccountId(String sfdcInternalAccountId) {
		this.sfdcInternalAccountId = sfdcInternalAccountId;
	}
	public String getTaxExemptReasonCd() {
		return taxExemptReasonCd;
	}
	public void setTaxExemptReasonCd(String taxExemptReasonCd) {
		this.taxExemptReasonCd = taxExemptReasonCd;
	}
}
