//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 08:10:09 PM IST 
//


package com.tip.estimationfilter.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilterForm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FilterForm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rangeUp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rangeDown" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="labelCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="elasticDbColumn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilterForm", propOrder = {
    "label",
    "value",
    "type",
    "rangeUp",
    "rangeDown",
    "labelCd",
    "elasticDbColumn"
})
public class FilterForm {

    protected String label;
    protected String value;
    protected String type;
    protected String rangeUp;
    protected String rangeDown;
    protected String labelCd;
    protected String elasticDbColumn;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the rangeUp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRangeUp() {
        return rangeUp;
    }

    /**
     * Sets the value of the rangeUp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRangeUp(String value) {
        this.rangeUp = value;
    }

    /**
     * Gets the value of the rangeDown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRangeDown() {
        return rangeDown;
    }

    /**
     * Sets the value of the rangeDown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRangeDown(String value) {
        this.rangeDown = value;
    }

    /**
     * Gets the value of the labelCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelCd() {
        return labelCd;
    }

    /**
     * Sets the value of the labelCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelCd(String value) {
        this.labelCd = value;
    }

    /**
     * Gets the value of the elasticDbColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElasticDbColumn() {
        return elasticDbColumn;
    }

    /**
     * Sets the value of the elasticDbColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElasticDbColumn(String value) {
        this.elasticDbColumn = value;
    }

}
