//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.02 at 08:37:14 PM IST 
//


package com.tip.asset.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplianceEquipDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplianceEquipDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="motDueDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nextInspDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplianceEquipDetails", propOrder = {
    "motDueDate",
    "nextInspDate"
})
public class ComplianceEquipDetails {

    protected String motDueDate;
    protected String nextInspDate;

    /**
     * Gets the value of the motDueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotDueDate() {
        return motDueDate;
    }

    /**
     * Sets the value of the motDueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotDueDate(String value) {
        this.motDueDate = value;
    }

    /**
     * Gets the value of the nextInspDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextInspDate() {
        return nextInspDate;
    }

    /**
     * Sets the value of the nextInspDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextInspDate(String value) {
        this.nextInspDate = value;
    }

}
