//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:14:50 AM IST 
//


package com.tip.inspection.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssetDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssetDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EquipmentNumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="CustomerEquipmentRefNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EquipmentLicenseNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EquipmentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EquipmentNumberHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerEquipmentRefNumberHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EquipmentLicenseNumberHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EquipmentTypeHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssetDetails", propOrder = {
    "title",
    "equipmentNumber",
    "customerEquipmentRefNumber",
    "equipmentLicenseNumber",
    "equipmentType",
    "equipmentNumberHeader",
    "customerEquipmentRefNumberHeader",
    "equipmentLicenseNumberHeader",
    "equipmentTypeHeader"
})
public class AssetDetails {

    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "EquipmentNumber")
    protected Integer equipmentNumber;
    @XmlElement(name = "CustomerEquipmentRefNumber")
    protected String customerEquipmentRefNumber;
    @XmlElement(name = "EquipmentLicenseNumber")
    protected String equipmentLicenseNumber;
    @XmlElement(name = "EquipmentType")
    protected String equipmentType;
    @XmlElement(name = "EquipmentNumberHeader")
    protected String equipmentNumberHeader;
    @XmlElement(name = "CustomerEquipmentRefNumberHeader")
    protected String customerEquipmentRefNumberHeader;
    @XmlElement(name = "EquipmentLicenseNumberHeader")
    protected String equipmentLicenseNumberHeader;
    @XmlElement(name = "EquipmentTypeHeader")
    protected String equipmentTypeHeader;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the equipmentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEquipmentNumber() {
        return equipmentNumber;
    }

    /**
     * Sets the value of the equipmentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEquipmentNumber(Integer value) {
        this.equipmentNumber = value;
    }

    /**
     * Gets the value of the customerEquipmentRefNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerEquipmentRefNumber() {
        return customerEquipmentRefNumber;
    }

    /**
     * Sets the value of the customerEquipmentRefNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerEquipmentRefNumber(String value) {
        this.customerEquipmentRefNumber = value;
    }

    /**
     * Gets the value of the equipmentLicenseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentLicenseNumber() {
        return equipmentLicenseNumber;
    }

    /**
     * Sets the value of the equipmentLicenseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentLicenseNumber(String value) {
        this.equipmentLicenseNumber = value;
    }

    /**
     * Gets the value of the equipmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentType() {
        return equipmentType;
    }

    /**
     * Sets the value of the equipmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentType(String value) {
        this.equipmentType = value;
    }

    /**
     * Gets the value of the equipmentNumberHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentNumberHeader() {
        return equipmentNumberHeader;
    }

    /**
     * Sets the value of the equipmentNumberHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentNumberHeader(String value) {
        this.equipmentNumberHeader = value;
    }

    /**
     * Gets the value of the customerEquipmentRefNumberHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerEquipmentRefNumberHeader() {
        return customerEquipmentRefNumberHeader;
    }

    /**
     * Sets the value of the customerEquipmentRefNumberHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerEquipmentRefNumberHeader(String value) {
        this.customerEquipmentRefNumberHeader = value;
    }

    /**
     * Gets the value of the equipmentLicenseNumberHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentLicenseNumberHeader() {
        return equipmentLicenseNumberHeader;
    }

    /**
     * Sets the value of the equipmentLicenseNumberHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentLicenseNumberHeader(String value) {
        this.equipmentLicenseNumberHeader = value;
    }

    /**
     * Gets the value of the equipmentTypeHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentTypeHeader() {
        return equipmentTypeHeader;
    }

    /**
     * Sets the value of the equipmentTypeHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentTypeHeader(String value) {
        this.equipmentTypeHeader = value;
    }

}
