//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.06 at 04:05:12 PM IST 
//


package com.tip.inspection.model;

import java.math.BigDecimal;

import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InspectionHeaderDataObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InspectionHeaderDataObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Device_Insp_Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Insp_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Customer_Nr" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Unit_Nr" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Insp_Date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Insp_Location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Insp_Loc_Longitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Insp_Loc_Latitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Insp_Loc_Altitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Insp_Driver_Company" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Insp_Remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="User_Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Time_Zone_Offset" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Insp_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="RejCd" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="RejMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InspectionHeaderDataObject", propOrder = {
    "deviceInspId",
    "inspType",
    "customerNr",
    "unitNr",
    "inspDate",
    "inspLocation",
    "inspLocLongitude",
    "inspLocLatitude",
    "inspLocAltitude",
    "inspDriverCompany",
    "inspRemarks",
    "userEmail",
    "timeZoneOffset",
    "inspId",
    "rejCd",
    "rejMsg"
})
public class InspectionHeaderDataObject {

    @XmlElement(name = "Device_Insp_Id")
    protected String deviceInspId;
    @XmlElement(name = "Insp_Type")
    protected String inspType;
    @XmlElement(name = "Customer_Nr")
    protected BigDecimal customerNr;
    @XmlElement(name = "Unit_Nr")
    protected int unitNr;
    @XmlElement(name = "Insp_Date")
    protected String inspDate;
    @XmlElement(name = "Insp_Location")
    protected String inspLocation;
    @XmlElement(name = "Insp_Loc_Longitude")
    protected BigDecimal inspLocLongitude;
    @XmlElement(name = "Insp_Loc_Latitude")
    protected BigDecimal inspLocLatitude;
    @XmlElement(name = "Insp_Loc_Altitude")
    protected BigDecimal inspLocAltitude;
    @XmlElement(name = "Insp_Driver_Company")
    protected String inspDriverCompany;
    @XmlElement(name = "Insp_Remarks")
    protected String inspRemarks;
    @NotNull(message="UserEmail is missing or null")
    @XmlElement(name = "User_Email", required = true)
    protected String userEmail;
    @XmlElement(name = "Time_Zone_Offset")
    protected String timeZoneOffset;
    /**
     * Gets the value of the deviceInspId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceInspId() {
        return deviceInspId;
    }

    /**
     * Sets the value of the deviceInspId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceInspId(String value) {
        this.deviceInspId = value;
    }

    /**
     * Gets the value of the inspType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInspType() {
        return inspType;
    }

    /**
     * Sets the value of the inspType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInspType(String value) {
        this.inspType = value;
    }

    /**
     * Gets the value of the customerNr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCustomerNr() {
        return customerNr;
    }

    /**
     * Sets the value of the customerNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCustomerNr(BigDecimal value) {
        this.customerNr = value;
    }

    /**
     * Gets the value of the unitNr property.
     * 
     */
    public int getUnitNr() {
        return unitNr;
    }

    /**
     * Sets the value of the unitNr property.
     * 
     */
    public void setUnitNr(int value) {
        this.unitNr = value;
    }

    /**
     * Gets the value of the inspDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInspDate() {
        return inspDate;
    }

    /**
     * Sets the value of the inspDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInspDate(String value) {
        this.inspDate = value;
    }

    /**
     * Gets the value of the inspLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInspLocation() {
        return inspLocation;
    }

    /**
     * Sets the value of the inspLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInspLocation(String value) {
        this.inspLocation = value;
    }

    /**
     * Gets the value of the inspLocLongitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInspLocLongitude() {
        return inspLocLongitude;
    }

    /**
     * Sets the value of the inspLocLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInspLocLongitude(BigDecimal value) {
        this.inspLocLongitude = value;
    }

    /**
     * Gets the value of the inspLocLatitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInspLocLatitude() {
        return inspLocLatitude;
    }

    /**
     * Sets the value of the inspLocLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInspLocLatitude(BigDecimal value) {
        this.inspLocLatitude = value;
    }

    /**
     * Gets the value of the inspLocAltitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInspLocAltitude() {
        return inspLocAltitude;
    }

    /**
     * Sets the value of the inspLocAltitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInspLocAltitude(BigDecimal value) {
        this.inspLocAltitude = value;
    }

    /**
     * Gets the value of the inspDriverCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInspDriverCompany() {
        return inspDriverCompany;
    }

    /**
     * Sets the value of the inspDriverCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInspDriverCompany(String value) {
        this.inspDriverCompany = value;
    }

    /**
     * Gets the value of the inspRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInspRemarks() {
        return inspRemarks;
    }

    /**
     * Sets the value of the inspRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInspRemarks(String value) {
        this.inspRemarks = value;
    }

    /**
     * Gets the value of the userEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * Sets the value of the userEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserEmail(String value) {
        this.userEmail = value;
    }

    /**
     * Gets the value of the timeZoneOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeZoneOffset() {
        return timeZoneOffset;
    }

    /**
     * Sets the value of the timeZoneOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeZoneOffset(String value) {
        this.timeZoneOffset = value;
    }


}
