//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:14:50 AM IST 
//


package com.tip.inspection.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InspectionItems complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InspectionItems">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Insp_Cd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Insp_Ind" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Insp_Ind_Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Insp_Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Insp_Comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InspectionItems", propOrder = {
    "inspCd",
    "inspInd",
    "inspIndDesc",
    "inspDesc",
    "inspComments"
})
public class InspectionItems {

    @XmlElement(name = "Insp_Cd")
    protected String inspCd;
    @XmlElement(name = "Insp_Ind")
    protected String inspInd;
    @XmlElement(name = "Insp_Ind_Desc")
    protected String inspIndDesc;
    @XmlElement(name = "Insp_Desc")
    protected String inspDesc;
    @XmlElement(name = "Insp_Comments")
    protected String inspComments;

    /**
     * Gets the value of the inspCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInspCd() {
        return inspCd;
    }

    /**
     * Sets the value of the inspCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInspCd(String value) {
        this.inspCd = value;
    }

    /**
     * Gets the value of the inspInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInspInd() {
        return inspInd;
    }

    /**
     * Sets the value of the inspInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInspInd(String value) {
        this.inspInd = value;
    }

    /**
     * Gets the value of the inspIndDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInspIndDesc() {
        return inspIndDesc;
    }

    /**
     * Sets the value of the inspIndDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInspIndDesc(String value) {
        this.inspIndDesc = value;
    }

    /**
     * Gets the value of the inspDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInspDesc() {
        return inspDesc;
    }

    /**
     * Sets the value of the inspDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInspDesc(String value) {
        this.inspDesc = value;
    }

    /**
     * Gets the value of the inspComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInspComments() {
        return inspComments;
    }

    /**
     * Sets the value of the inspComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInspComments(String value) {
        this.inspComments = value;
    }

}
