//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.10 at 07:01:15 PM IST 
//


package com.tip.estimation.model;

import java.math.BigDecimal;

public class EnrichTyreSpecsObject {

    protected BigDecimal estimationId;
    protected Integer estnWOId;
    protected Integer estnWOTId;
    protected Integer tyreSpecgrpId;
    protected Integer tyreSpecsubgrpId;
    protected Integer tyreSpecItemId;
    protected String tyreSize;
    protected Integer application;
    protected String brand;
    protected String tyreStatus;
    protected String chargeType;
    protected Integer lostMM;
    protected Integer version;
    protected Integer supplementary;
    protected BigDecimal charges;
    protected Boolean showHide;
    protected String isApproved;
    protected String isRejected;
    protected Integer rejectedReason;
    protected String ssoId;
	public BigDecimal getEstimationId() {
		return estimationId;
	}
	public void setEstimationId(BigDecimal estimationId) {
		this.estimationId = estimationId;
	}
	public Integer getEstnWOId() {
		return estnWOId;
	}
	public void setEstnWOId(Integer estnWOId) {
		this.estnWOId = estnWOId;
	}
	public Integer getEstnWOTId() {
		return estnWOTId;
	}
	public void setEstnWOTId(Integer estnWOTId) {
		this.estnWOTId = estnWOTId;
	}
	public Integer getTyreSpecgrpId() {
		return tyreSpecgrpId;
	}
	public void setTyreSpecgrpId(Integer tyreSpecgrpId) {
		this.tyreSpecgrpId = tyreSpecgrpId;
	}
	public Integer getTyreSpecsubgrpId() {
		return tyreSpecsubgrpId;
	}
	public void setTyreSpecsubgrpId(Integer tyreSpecsubgrpId) {
		this.tyreSpecsubgrpId = tyreSpecsubgrpId;
	}
	public Integer getTyreSpecItemId() {
		return tyreSpecItemId;
	}
	public void setTyreSpecItemId(Integer tyreSpecItemId) {
		this.tyreSpecItemId = tyreSpecItemId;
	}
	public String getTyreSize() {
		return tyreSize;
	}
	public void setTyreSize(String tyreSize) {
		this.tyreSize = tyreSize;
	}
	public Integer getApplication() {
		return application;
	}
	public void setApplication(Integer application) {
		this.application = application;
	}
	public String getBrand() {
		return brand;
	}
	public void setBrand(String brand) {
		this.brand = brand;
	}
	public String getTyreStatus() {
		return tyreStatus;
	}
	public void setTyreStatus(String tyreStatus) {
		this.tyreStatus = tyreStatus;
	}
	public String getChargeType() {
		return chargeType;
	}
	public void setChargeType(String chargeType) {
		this.chargeType = chargeType;
	}
	public Integer getLostMM() {
		return lostMM;
	}
	public void setLostMM(Integer lostMM) {
		this.lostMM = lostMM;
	}
	public Integer getVersion() {
		return version;
	}
	public void setVersion(Integer version) {
		this.version = version;
	}
	public Integer getSupplementary() {
		return supplementary;
	}
	public void setSupplementary(Integer supplementary) {
		this.supplementary = supplementary;
	}
	public BigDecimal getCharges() {
		return charges;
	}
	public void setCharges(BigDecimal charges) {
		this.charges = charges;
	}
	public Boolean isShowHide() {
		return showHide;
	}
	public void setShowHide(Boolean showHide) {
		this.showHide = showHide;
	}
	public String getIsApproved() {
		return isApproved;
	}
	public void setIsApproved(String isApproved) {
		this.isApproved = isApproved;
	}
	public String getIsRejected() {
		return isRejected;
	}
	public void setIsRejected(String isRejected) {
		this.isRejected = isRejected;
	}
	public Integer getRejectedReason() {
		return rejectedReason;
	}
	public void setRejectedReason(Integer rejectedReason) {
		this.rejectedReason = rejectedReason;
	}
	public String getSsoId() {
		return ssoId;
	}
	public void setSsoId(String ssoId) {
		this.ssoId = ssoId;
	}

    
    
}