//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.17 at 08:05:18 PM IST 
//


package com.tip.estimation.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FetchReadingsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FetchReadingsResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EstnTyreRdngList" type="{http://www.example.org/FetchReadings}EstnTyreRdngObject" maxOccurs="unbounded"/>
 *         &lt;element name="EstnBrakeRdngList" type="{http://www.example.org/FetchReadings}EstnBrakeRdngObject" maxOccurs="unbounded"/>
 *         &lt;element name="EstnAssetRdngList" type="{http://www.example.org/FetchReadings}EstnAssetRdngObject" maxOccurs="unbounded"/>
 *         &lt;element name="EstnOperRdngList" type="{http://www.example.org/FetchReadings}EstnOperRdngObject" maxOccurs="unbounded"/>
 *         &lt;element name="EstnTailliftRdngList" type="{http://www.example.org/FetchReadings}EstnTailliftRdngObject" maxOccurs="unbounded"/>
 *         &lt;element name="EstnFridgeRdngList" type="{http://www.example.org/FetchReadings}EstnFridgeRdngObject" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FetchReadingsResponse", propOrder = {
    "estnTyreRdngList",
    "estnBrakeRdngList",
    "estnAssetRdngList",
    "estnOperRdngList",
    "estnTailliftRdngList",
    "estnFridgeRdngList"
})
public class FetchReadingsResponse {

    @XmlElement(name = "EstnTyreRdngList", required = true)
    protected List<EstnTyreRdngObject> estnTyreRdngList;
    @XmlElement(name = "EstnBrakeRdngList", required = true)
    protected List<EstnBrakeRdngObject> estnBrakeRdngList;
    @XmlElement(name = "EstnAssetRdngList", required = true)
    protected List<EstnAssetRdngObject> estnAssetRdngList;
    @XmlElement(name = "EstnOperRdngList", required = true)
    protected List<EstnOperRdngObject> estnOperRdngList;
    @XmlElement(name = "EstnTailliftRdngList", required = true)
    protected List<EstnTailliftRdngObject> estnTailliftRdngList;
    @XmlElement(name = "EstnFridgeRdngList", required = true)
    protected List<EstnFridgeRdngObject> estnFridgeRdngList;

    /**
     * Gets the value of the estnTyreRdngList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estnTyreRdngList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstnTyreRdngList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstnTyreRdngObject }
     * 
     * 
     */
    public List<EstnTyreRdngObject> getEstnTyreRdngList() {
        if (estnTyreRdngList == null) {
            estnTyreRdngList = new ArrayList<EstnTyreRdngObject>();
        }
        return this.estnTyreRdngList;
    }

    /**
     * Gets the value of the estnBrakeRdngList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estnBrakeRdngList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstnBrakeRdngList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstnBrakeRdngObject }
     * 
     * 
     */
    public List<EstnBrakeRdngObject> getEstnBrakeRdngList() {
        if (estnBrakeRdngList == null) {
            estnBrakeRdngList = new ArrayList<EstnBrakeRdngObject>();
        }
        return this.estnBrakeRdngList;
    }

    /**
     * Gets the value of the estnAssetRdngList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estnAssetRdngList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstnAssetRdngList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstnAssetRdngObject }
     * 
     * 
     */
    public List<EstnAssetRdngObject> getEstnAssetRdngList() {
        if (estnAssetRdngList == null) {
            estnAssetRdngList = new ArrayList<EstnAssetRdngObject>();
        }
        return this.estnAssetRdngList;
    }

    /**
     * Gets the value of the estnOperRdngList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estnOperRdngList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstnOperRdngList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstnOperRdngObject }
     * 
     * 
     */
    public List<EstnOperRdngObject> getEstnOperRdngList() {
        if (estnOperRdngList == null) {
            estnOperRdngList = new ArrayList<EstnOperRdngObject>();
        }
        return this.estnOperRdngList;
    }

    /**
     * Gets the value of the estnTailliftRdngList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estnTailliftRdngList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstnTailliftRdngList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstnTailliftRdngObject }
     * 
     * 
     */
    public List<EstnTailliftRdngObject> getEstnTailliftRdngList() {
        if (estnTailliftRdngList == null) {
            estnTailliftRdngList = new ArrayList<EstnTailliftRdngObject>();
        }
        return this.estnTailliftRdngList;
    }

    /**
     * Gets the value of the estnFridgeRdngList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estnFridgeRdngList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstnFridgeRdngList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstnFridgeRdngObject }
     * 
     * 
     */
    public List<EstnFridgeRdngObject> getEstnFridgeRdngList() {
        if (estnFridgeRdngList == null) {
            estnFridgeRdngList = new ArrayList<EstnFridgeRdngObject>();
        }
        return this.estnFridgeRdngList;
    }

}
