//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.26 at 08:05:01 PM IST 
//


package com.tip.estimation.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tyre complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tyre">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EstWoId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="EstWotId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="tyreSize" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="application" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tyreStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ChargeType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lostmm" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="tyrePrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="fees" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="feesPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="cashingValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cashingPrice" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="tyreSpecgrpId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="tyreSpecsubgrpId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="tyreSpecItemId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tyre", propOrder = {
    "estWoId",
    "estWotId",
    "tyreSize",
    "application",
    "brand",
    "tyreStatus",
    "chargeType",
    "lostmm",
    "tyrePrice",
    "fees",
    "feesPrice",
    "cashingValue",
    "cashingPrice",
    "tyreSpecgrpId",
    "tyreSpecsubgrpId",
    "tyreSpecItemId"
})
public class Tyre {

    @XmlElement(name = "EstWoId")
    protected Integer estWoId;
    @XmlElement(name = "EstWotId")
    protected Integer estWotId;
    protected String tyreSize;
    protected Integer application;
    protected String brand;
    protected String tyreStatus;
    @XmlElement(name = "ChargeType")
    protected String chargeType;
    protected Integer lostmm;
    protected BigDecimal tyrePrice;
    protected String fees;
    protected BigDecimal feesPrice;
    protected String cashingValue;
    protected Integer cashingPrice;
    protected Integer tyreSpecgrpId;
    protected Integer tyreSpecsubgrpId;
    protected Integer tyreSpecItemId;

    /**
     * Gets the value of the estWoId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEstWoId() {
        return estWoId;
    }

    /**
     * Sets the value of the estWoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEstWoId(Integer value) {
        this.estWoId = value;
    }

    /**
     * Gets the value of the estWotId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEstWotId() {
        return estWotId;
    }

    /**
     * Sets the value of the estWotId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEstWotId(Integer value) {
        this.estWotId = value;
    }

    /**
     * Gets the value of the tyreSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTyreSize() {
        return tyreSize;
    }

    /**
     * Sets the value of the tyreSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTyreSize(String value) {
        this.tyreSize = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setApplication(Integer value) {
        this.application = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the tyreStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTyreStatus() {
        return tyreStatus;
    }

    /**
     * Sets the value of the tyreStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTyreStatus(String value) {
        this.tyreStatus = value;
    }

    /**
     * Gets the value of the chargeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * Sets the value of the chargeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeType(String value) {
        this.chargeType = value;
    }

    /**
     * Gets the value of the lostmm property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLostmm() {
        return lostmm;
    }

    /**
     * Sets the value of the lostmm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLostmm(Integer value) {
        this.lostmm = value;
    }

    /**
     * Gets the value of the tyrePrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTyrePrice() {
        return tyrePrice;
    }

    /**
     * Sets the value of the tyrePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTyrePrice(BigDecimal value) {
        this.tyrePrice = value;
    }

    /**
     * Gets the value of the fees property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFees() {
        return fees;
    }

    /**
     * Sets the value of the fees property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFees(String value) {
        this.fees = value;
    }

    /**
     * Gets the value of the feesPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFeesPrice() {
        return feesPrice;
    }

    /**
     * Sets the value of the feesPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFeesPrice(BigDecimal value) {
        this.feesPrice = value;
    }

    /**
     * Gets the value of the cashingValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCashingValue() {
        return cashingValue;
    }

    /**
     * Sets the value of the cashingValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCashingValue(String value) {
        this.cashingValue = value;
    }

    /**
     * Gets the value of the cashingPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCashingPrice() {
        return cashingPrice;
    }

    /**
     * Sets the value of the cashingPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCashingPrice(Integer value) {
        this.cashingPrice = value;
    }

    /**
     * Gets the value of the tyreSpecgrpId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTyreSpecgrpId() {
        return tyreSpecgrpId;
    }

    /**
     * Sets the value of the tyreSpecgrpId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTyreSpecgrpId(Integer value) {
        this.tyreSpecgrpId = value;
    }

    /**
     * Gets the value of the tyreSpecsubgrpId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTyreSpecsubgrpId() {
        return tyreSpecsubgrpId;
    }

    /**
     * Sets the value of the tyreSpecsubgrpId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTyreSpecsubgrpId(Integer value) {
        this.tyreSpecsubgrpId = value;
    }

    /**
     * Gets the value of the tyreSpecItemId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTyreSpecItemId() {
        return tyreSpecItemId;
    }

    /**
     * Sets the value of the tyreSpecItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTyreSpecItemId(Integer value) {
        this.tyreSpecItemId = value;
    }

}
