//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.21 at 07:45:07 PM IST 
//


package com.tip.estimation.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VersionDetailsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VersionDetailsResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EstnVersionlist" type="{http://www.example.org/EstnVersionDetails}EstnVersnObject" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VersionDetailsResponse", propOrder = {
    "estnVersionlist"
})
public class VersionDetailsResponse {

    @XmlElement(name = "EstnVersionlist", required = true)
    protected List<EstnVersnObject> estnVersionlist;

    /**
     * Gets the value of the estnVersionlist property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estnVersionlist property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstnVersionlist().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstnVersnObject }
     * 
     * 
     */
    public List<EstnVersnObject> getEstnVersionlist() {
        if (estnVersionlist == null) {
            estnVersionlist = new ArrayList<EstnVersnObject>();
        }
        return this.estnVersionlist;
    }

}
