//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 01:59:24 PM IST 
//


package com.tip.equipmentdetails.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Filter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Filter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="valueList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="rangeLt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rangeGt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="includeLower" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="includeUpper" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="labelCd" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="filterCd" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="elasticDbField" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Filter", propOrder = {
    "operation",
    "condition",
    "value",
    "valueList",
    "rangeLt",
    "rangeGt",
    "includeLower",
    "includeUpper",
    "labelCd",
    "filterCd",
    "elasticDbField"
})
public class Filter {

    protected String operation;
    protected String condition;
    protected String value;
    @XmlElement(required = true)
    protected List<String> valueList;
    protected String rangeLt;
    protected String rangeGt;
    protected Boolean includeLower;
    protected Boolean includeUpper;
    protected Integer labelCd;
    protected Integer filterCd;
    protected String elasticDbField;

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the valueList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valueList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValueList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValueList() {
        if (valueList == null) {
            valueList = new ArrayList<String>();
        }
        return this.valueList;
    }

    /**
     * Gets the value of the rangeLt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRangeLt() {
        return rangeLt;
    }

    /**
     * Sets the value of the rangeLt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRangeLt(String value) {
        this.rangeLt = value;
    }

    /**
     * Gets the value of the rangeGt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRangeGt() {
        return rangeGt;
    }

    /**
     * Sets the value of the rangeGt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRangeGt(String value) {
        this.rangeGt = value;
    }

    /**
     * Gets the value of the includeLower property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeLower() {
        return includeLower;
    }

    /**
     * Sets the value of the includeLower property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeLower(Boolean value) {
        this.includeLower = value;
    }

    /**
     * Gets the value of the includeUpper property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeUpper() {
        return includeUpper;
    }

    /**
     * Sets the value of the includeUpper property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeUpper(Boolean value) {
        this.includeUpper = value;
    }

    /**
     * Gets the value of the labelCd property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLabelCd() {
        return labelCd;
    }

    /**
     * Sets the value of the labelCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLabelCd(Integer value) {
        this.labelCd = value;
    }

    /**
     * Gets the value of the filterCd property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFilterCd() {
        return filterCd;
    }

    /**
     * Sets the value of the filterCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFilterCd(Integer value) {
        this.filterCd = value;
    }

    /**
     * Gets the value of the elasticDbField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElasticDbField() {
        return elasticDbField;
    }

    /**
     * Sets the value of the elasticDbField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElasticDbField(String value) {
        this.elasticDbField = value;
    }

}
