//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.08 at 04:07:19 PM IST 
//


package com.tip.equipmentdetails.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SaveProfileSettingsRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SaveProfileSettingsRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ssoId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fieldApp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FieldLabelLst" type="{http://www.example.org/FetchFilterDetails}FieldLabel" maxOccurs="unbounded"/>
 *         &lt;element name="fetchFilterDetails" type="{http://www.example.org/FetchFilterDetails}FetchFilterDetails" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SaveProfileSettingsRequest", propOrder = {
    "ssoId",
    "fieldApp",
    "fieldLabelLst",
    "fetchFilterDetails"
})
public class SaveProfileSettingsRequest {

    protected String ssoId;
    protected String fieldApp;
    @XmlElement(name = "FieldLabelLst", required = true)
    protected List<FieldLabel> fieldLabelLst;
    protected FetchFilterDetails fetchFilterDetails;

    /**
     * Gets the value of the ssoId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsoId() {
        return ssoId;
    }

    /**
     * Sets the value of the ssoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsoId(String value) {
        this.ssoId = value;
    }

    /**
     * Gets the value of the fieldApp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldApp() {
        return fieldApp;
    }

    /**
     * Sets the value of the fieldApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldApp(String value) {
        this.fieldApp = value;
    }

    /**
     * Gets the value of the fieldLabelLst property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldLabelLst property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldLabelLst().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldLabel }
     * 
     * 
     */
    public List<FieldLabel> getFieldLabelLst() {
        if (fieldLabelLst == null) {
            fieldLabelLst = new ArrayList<FieldLabel>();
        }
        return this.fieldLabelLst;
    }

    /**
     * Gets the value of the fetchFilterDetails property.
     * 
     * @return
     *     possible object is
     *     {@link FetchFilterDetails }
     *     
     */
    public FetchFilterDetails getFetchFilterDetails() {
        return fetchFilterDetails;
    }

    /**
     * Sets the value of the fetchFilterDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link FetchFilterDetails }
     *     
     */
    public void setFetchFilterDetails(FetchFilterDetails value) {
        this.fetchFilterDetails = value;
    }

}
