spring:
  profiles.active: default
---
spring:
  profiles: default
  datasource:
    hikari:
      connection-test-query: select 1
  jpa:
   properties:
    hibernate:
     current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
     ddl-auto: update
     dialect: org.hibernate.dialect.SybaseDialect
    autocommit: false 
   show-sql: true
    
spring.datasource:
  driverClassName: com.sybase.jdbc3.jdbc.SybDriver
  url: jdbc:sybase:Tds:10.236.187.13:5555/OPSals
  username: devuser
  password: rizzo123

  
---
spring:
  profiles: dev
  datasource:
    hikari:
      connection-test-query: select 1
  jpa:
   properties:
    hibernate:
     current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
     ddl-auto: update
     dialect: org.hibernate.dialect.SybaseDialect
    autocommit: false 
   show-sql: true
    
spring.datasource:
  driverClassName: com.sybase.jdbc3.jdbc.SybDriver
  url: jdbc:sybase:Tds:10.236.187.13:5555/OPSals
  username: devuser
  password: rizzo123


---
spring:
  profiles: uat
  datasource:
    hikari:
      connection-test-query: select 1
  jpa:
   properties:
    hibernate:
     current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
     ddl-auto: update
     dialect: org.hibernate.dialect.SybaseDialect
    autocommit: false 
   show-sql: true
    
spring.datasource:
  driverClassName: com.sybase.jdbc3.jdbc.SybDriver
  url: jdbc:sybase:Tds:10.236.188.10:7725/OPSals
  username: uatuser
  password: test123
  
  