//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 08:32:30 PM IST 
//


package com.tip.estimationreport.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImageDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EstWoId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EstWoTaskId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhotoType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhotoName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhotoLoc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageDetails", propOrder = {
    "estWoId",
    "estWoTaskId",
    "photoType",
    "photoName",
    "photoLoc"
})
public class ImageDetails {

    @XmlElement(name = "EstWoId")
    protected String estWoId;
    @XmlElement(name = "EstWoTaskId")
    protected String estWoTaskId;
    @XmlElement(name = "PhotoType")
    protected String photoType;
    @XmlElement(name = "PhotoName")
    protected String photoName;
    @XmlElement(name = "PhotoLoc")
    protected String photoLoc;

    /**
     * Gets the value of the estWoId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstWoId() {
        return estWoId;
    }

    /**
     * Sets the value of the estWoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstWoId(String value) {
        this.estWoId = value;
    }

    /**
     * Gets the value of the estWoTaskId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstWoTaskId() {
        return estWoTaskId;
    }

    /**
     * Sets the value of the estWoTaskId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstWoTaskId(String value) {
        this.estWoTaskId = value;
    }

    /**
     * Gets the value of the photoType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhotoType() {
        return photoType;
    }

    /**
     * Sets the value of the photoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhotoType(String value) {
        this.photoType = value;
    }

    /**
     * Gets the value of the photoName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhotoName() {
        return photoName;
    }

    /**
     * Sets the value of the photoName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhotoName(String value) {
        this.photoName = value;
    }

    /**
     * Gets the value of the photoLoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhotoLoc() {
        return photoLoc;
    }

    /**
     * Sets the value of the photoLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhotoLoc(String value) {
        this.photoLoc = value;
    }

}
